### ISSUE TITLE
MobilePay-AppSwitch-SDK cannot be imported in Swift Project

### ISSUE THREAD

**Issue by mihirpmehta** [MobilePayDev/MobilePay-AppSwitch-SDK#6]
If you create the Swift only project and try to integrate MobilePay-AppSwitch-SDK via pods. You cannot import the Module. You need to create bridging header compulsory.

**Comment by lmktrifork** [comment]
The app developer needs to create the bridging header in the app - not the dependency (Pod).
Please read the following:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
